### ISSUE TITLE
FR15.  Pre-plot reservations and waitlist parties

### ISSUE THREAD

**Issue by MichaelBeher** [WSU-4110/SimpleRes#20]
|FR15.  Pre-plot reservations and waitlist parties|
|---|
|**Goal**: FR15 allows the user to pre-plot reservations and waitlist parties 
**Stakeholders:** Hosts|
| **Description:** The user can pre-plot parties from the reservation and waitlist without removing those parties from the waitlist to the table |
| **Origin:** Based on initial project software requirements specification meeting|
| **Version:** 1.0  |
|**Date:** 09/17/2019
|  **Priority:** 2 |

**Comment by bellapense** [comment]
Group decided that this feature does not fit into our UI design. We received permission to remove this issue from our project.
